version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*net/http.Response.Body).Close
        - (net/http.ResponseWriter).Write
